import type { Metadata } from 'next';
import Link from 'next/link';
import './globals.css';
import { poppins } from '@/utils/fonts';

export const metadata: Metadata = {
  title: 'CS Society Ashoka',
  description: 'Generated by create next app',
};

function NavItem({ href, children }: { href: string; children: React.ReactNode }) {
  return (
    <li className={`font-extralight text-shadow-hover transition-all duration-150 text-center text-base sm:text-[17px] lg:text-lg`}>
      <Link href={href}>{children}</Link>
    </li>
  );
}

function NavBar() {
  return (
    <div className={`bg-transparent pt-[4vh] pb-[6vh] px-4 sm:px-8 md:px-12 lg:px-16`}>
      <ul className={`flex items-center justify-end gap-x-4 sm:gap-x-8 md:gap-x-12`}>
        <NavItem href='/'>Home</NavItem>
        <NavItem href='/about'>About</NavItem>
        <NavItem href='/events'>Events</NavItem>
        <NavItem href='/resources'>Resources</NavItem>
      </ul>
    </div>
  );
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className={`h-full`}>
      <body className={`${poppins.className} bg-background h-full`}>
        {/* <div className={`text-text px-4 sm:px-8 md:px-12 lg:px-16`}> */}
        <div className={`text-text h-full w-full`}>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
