import type { Metadata } from "next"; 
import "../app/globals.css"; 
import { inter, jetbrainsMono } from "@/utils/fonts";
import { Navbar } from "../components/navbar/Navbar";
import { Footer } from "../components/footer";
export const metadata: Metadata = {
  title: "CS Society @ Ashoka",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${jetbrainsMono.variable} h-full`}>
      <body className={`${inter.className} bg-background h-full background-div`}>
        {/* <div className={`text-text px-4 sm:px-8 md:px-12 lg:px-16`}> */}
        <div className={`text-text h-full w-full`}>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
