import './globals.css';
import type { Metadata } from 'next';
import { poppins } from '@/utils/fonts';
import NavBar from '@/components/Navbar';

export const metadata: Metadata = {
  title: 'CS Society Ashoka',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className={`h-full`}>
      <body className={`${poppins.className} bg-background h-full`}>
        {/* <div className={`text-text px-4 sm:px-8 md:px-12 lg:px-16`}> */}
        <div className={`text-text h-full w-full`}>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
